name: Build and Release to GitHub

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}
  GITHUB_REPO: nash87/cv-manager-releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev nsis

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Update version in files
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          # Update wails.json
          sed -i "s/\"productVersion\": \".*\"/\"productVersion\": \"$VERSION\"/" wails.json
          # Update version.go constants (simplified)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          sed -i "s/MajorVersion = .*/MajorVersion = $MAJOR/" version.go
          sed -i "s/MinorVersion = .*/MinorVersion = $MINOR/" version.go
          sed -i "s/PatchVersion = .*/PatchVersion = $PATCH/" version.go

      - name: Build Windows executable
        run: |
          wails build -platform windows/amd64 -ldflags "-X main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.GitCommit=$GITHUB_SHA"

      - name: Calculate SHA256
        id: sha
        run: |
          SHA256=$(sha256sum build/bin/cv-manager.exe | cut -d ' ' -f1)
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
          SIZE_MB=$(du -m build/bin/cv-manager.exe | cut -f1)
          echo "SIZE_MB=$SIZE_MB" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: notes
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          # Extract changelog from version.go for this version
          go run -mod=mod scripts/extract-changelog.go $VERSION > release_notes.md || echo "WYSIWYG Editor Update" > release_notes.md
          cat release_notes.md

      - name: Generate version.json
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          SHA256=${{ steps.sha.outputs.SHA256 }}
          SIZE_MB=${{ steps.sha.outputs.SIZE_MB }}
          DATE=$(date -u +%Y-%m-%d)
          cat > version.json << EOF
          {
            "latest_version": "$VERSION",
            "release_date": "$DATE",
            "download_url": "https://github.com/${{ env.GITHUB_REPO }}/releases/download/v$VERSION/cv-manager.exe",
            "changelog_url": "https://github.com/${{ env.GITHUB_REPO }}/releases/tag/v$VERSION",
            "release_notes": "$(cat release_notes.md | head -1)",
            "sha256": "$SHA256",
            "size_mb": $SIZE_MB,
            "is_required": false
          }
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ env.GITHUB_REPO }}
          token: ${{ env.GITHUB_TOKEN }}
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: CV Manager v${{ steps.version.outputs.VERSION }}
          body_path: release_notes.md
          files: |
            build/bin/cv-manager.exe
            version.json
          draft: false
          prerelease: false

      - name: Update version.json in release repo
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          # Clone the releases repo
          git clone https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ env.GITHUB_REPO }}.git releases-repo
          cd releases-repo
          cp ../version.json .
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git add version.json
          git commit -m "Update version.json to v$VERSION" || echo "No changes to commit"
          git push origin main
