name: Push Release to GitHub

on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
  GITHUB_REPO: nash87/cv-manager-releases

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION"

      - name: Get Release Notes from Commits
        id: notes
        run: |
          # Get last 10 commit messages for release notes
          echo "## CV Manager v${{ steps.version.outputs.VERSION }}" > release_notes.md
          echo "" >> release_notes.md
          echo "### Changes" >> release_notes.md
          git log --oneline -10 --pretty=format:"- %s" >> release_notes.md
          echo "" >> release_notes.md
          cat release_notes.md

      - name: Verify build artifacts exist
        run: |
          if [ ! -f "build/bin/cv-manager.exe" ]; then
            echo "ERROR: cv-manager.exe not found! Build locally first."
            exit 1
          fi
          if [ ! -f "version.json" ]; then
            echo "ERROR: version.json not found!"
            exit 1
          fi
          echo "Build artifacts found:"
          ls -la build/bin/cv-manager.exe
          cat version.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ env.GITHUB_REPO }}
          token: ${{ env.GH_TOKEN }}
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: CV Manager v${{ steps.version.outputs.VERSION }}
          body_path: release_notes.md
          files: |
            build/bin/cv-manager.exe
            version.json
          draft: false
          prerelease: false

      - name: Update version.json in release repo
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          git clone https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ env.GITHUB_REPO }}.git releases-repo
          cd releases-repo
          cp ../version.json .
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git add version.json
          git commit -m "Release v$VERSION - $(head -1 ../release_notes.md)" || echo "No changes"
          git push origin main
