name: Push Release to GitHub

on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
  GITHUB_REPO: nash87/cv-manager-releases

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION"

      - name: Get Release Notes from Commits
        run: |
          echo "## CV Manager v${{ steps.version.outputs.VERSION }}" > release_notes.md
          echo "" >> release_notes.md
          echo "### Changes" >> release_notes.md
          git log --oneline -10 --pretty=format:"- %s" >> release_notes.md
          echo "" >> release_notes.md
          cat release_notes.md

      - name: Verify build artifacts exist
        run: |
          if [ ! -f "build/bin/cv-manager.exe" ]; then
            echo "ERROR: cv-manager.exe not found! Build locally first."
            exit 1
          fi
          if [ ! -f "version.json" ]; then
            echo "ERROR: version.json not found!"
            exit 1
          fi
          echo "Build artifacts found:"
          ls -lh build/bin/cv-manager.exe
          cat version.json

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create GitHub Release
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}

          # Delete existing release if exists
          gh release delete "v$VERSION" --repo $GITHUB_REPO --yes 2>/dev/null || true

          # Create new release with assets
          gh release create "v$VERSION" \
            --repo $GITHUB_REPO \
            --title "CV Manager v$VERSION" \
            --notes-file release_notes.md \
            build/bin/cv-manager.exe \
            version.json

      - name: Update version.json in release repo
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          git clone https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ env.GITHUB_REPO }}.git releases-repo
          cd releases-repo
          cp ../version.json .
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"
          git add version.json
          git commit -m "Release v$VERSION" || echo "No changes"
          git push origin main
